# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pattern_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 370, 581, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_1.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_1.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 450, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGeneral = QtWidgets.QAction(MainWindow)
        self.actionGeneral.setObjectName("actionGeneral")
        self.actionE_mail_account = QtWidgets.QAction(MainWindow)
        self.actionE_mail_account.setObjectName("actionE_mail_account")
        self.actionProject_settings = QtWidgets.QAction(MainWindow)
        self.actionProject_settings.setObjectName("actionProject_settings")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_recent_projects = QtWidgets.QAction(MainWindow)
        self.actionOpen_recent_projects.setObjectName("actionOpen_recent_projects")
        self.actionAbout_programm = QtWidgets.QAction(MainWindow)
        self.actionAbout_programm.setObjectName("actionAbout_programm")
        self.actionProgramm_guide = QtWidgets.QAction(MainWindow)
        self.actionProgramm_guide.setObjectName("actionProgramm_guide")
        self.actionConnect_with_author = QtWidgets.QAction(MainWindow)
        self.actionConnect_with_author.setObjectName("actionConnect_with_author")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_recent_projects)
        self.menuSettings.addAction(self.actionGeneral)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionE_mail_account)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionProject_settings)
        self.menuHelp.addAction(self.actionAbout_programm)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionProgramm_guide)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionShortcuts)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionConnect_with_author)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Вствьте ссылку на страницу книги"))
        self.lineEdit.setText(_translate("MainWindow", "Вствьте ссылку на страницу книги"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionGeneral.setText(_translate("MainWindow", "General"))
        self.actionE_mail_account.setText(_translate("MainWindow", "E-mail account"))
        self.actionProject_settings.setText(_translate("MainWindow", "Project settings"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_recent_projects.setText(_translate("MainWindow", "Open recent projects"))
        self.actionAbout_programm.setText(_translate("MainWindow", "About programm"))
        self.actionProgramm_guide.setText(_translate("MainWindow", "Programm guide"))
        self.actionConnect_with_author.setText(_translate("MainWindow", "Connect with author"))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts"))

